"""
MPLADS Fraud Detection Model
Smart India Hackathon (SIH) Prototype

This module implements an unsupervised anomaly detection pipeline using Isolation Forest
to detect potential fraudulent activities, ghost works, fund siphoning, and budget
overruns in Member of Parliament Local Area Development Scheme (MPLADS) projects.

Pipeline Steps:
1. Load dataset (CSV or DataFrame) with automatic column alias normalization.
2. Engineer domain-specific MPLADS fraud indicators (fund-progress gap, cost overruns).
3. Train an Isolation Forest model on normalized features.
4. Detect anomalous transactions.
5. Compute a human-interpretable 0-100 Risk Score.
6. Generate transparent, natural-language reasons explaining why a project is flagged.
"""

import os
from typing import Dict, List, Optional, Tuple, Union

import joblib
import numpy as np
import pandas as pd
from sklearn.ensemble import IsolationForest
from sklearn.preprocessing import RobustScaler


# ---------------------------------------------------------------------------
# 1. Schema & Column Normalization
# ---------------------------------------------------------------------------

# Column aliases to ensure seamless integration with datasets generated by teammates
COLUMN_ALIASES: Dict[str, List[str]] = {
    "project_id": ["project_id", "work_id", "id", "work_code", "project_code"],
    "category": [
        "category",
        "sector",
        "work_category",
        "work_type",
        "scheme_sector",
        "project_category",
    ],
    "constituency": ["constituency", "constituency_name", "district", "lok_sabha_constituency"],
    "state": ["state", "state_name"],
    "recommended_amount": [
        "recommended_amount",
        "recom_amount",
        "estimated_amount",
        "estimated_cost",
        "cost_recommended",
    ],
    "sanctioned_amount": [
        "sanctioned_amount",
        "sanct_amount",
        "approved_amount",
        "approved_cost",
        "sanction_cost",
    ],
    "released_amount": [
        "released_amount",
        "release_amount",
        "funds_released",
        "installment_released",
    ],
    "expenditure_amount": [
        "expenditure_amount",
        "expenditure",
        "actual_expenditure",
        "amount_spent",
        "spent_amount",
        "funds_utilized",
        "actual_utilized_amount",
        "claimed_utilized_amount",
    ],
    "physical_progress_pct": [
        "physical_progress_pct",
        "physical_progress",
        "progress_percentage",
        "progress_pct",
        "progress",
        "physical_progress_percent",
        "completion_percentage",
    ],
    "contractor_id": [
        "contractor_id",
        "contractor",
        "agency_id",
        "agency_name",
        "implementing_agency",
        "contractor_name",
        "vendor_id",
    ],
    "sanction_date": ["sanction_date", "date_sanctioned"],
    "expected_completion_date": ["expected_completion_date", "target_completion_date", "target_date"],
    "actual_completion_date": ["actual_completion_date", "completion_date", "date_completed"],
    "gps_distance_km": ["gps_distance_km", "distance_km", "gps_deviation_km"],
    "duplicate_photo_flag": ["duplicate_photo_flag", "duplicate_photo", "is_duplicate_photo"],
}


def normalize_columns(df: pd.DataFrame) -> pd.DataFrame:
    """
    Standardizes dataframe column names using alias matching.
    Ensures team compatibility regardless of minor naming differences in CSVs.
    """
    df = df.copy()
    cleaned_cols = {col: str(col).strip().lower().replace(" ", "_") for col in df.columns}
    df.rename(columns=cleaned_cols, inplace=True)

    rename_map = {}
    for standard_name, aliases in COLUMN_ALIASES.items():
        if standard_name in df.columns:
            continue
        for alias in aliases:
            if alias in df.columns:
                rename_map[alias] = standard_name
                break

    if rename_map:
        df.rename(columns=rename_map, inplace=True)

    return df


def load_dataset(source: Union[str, pd.DataFrame]) -> pd.DataFrame:
    """
    Loads an MPLADS dataset from a CSV path or accepts an existing DataFrame,
    normalizes column headers, and performs essential validation.
    """
    if isinstance(source, pd.DataFrame):
        df = source.copy()
    elif isinstance(source, str):
        if not os.path.exists(source):
            raise FileNotFoundError(f"Dataset file not found at: {source}")
        df = pd.read_csv(source)
    else:
        raise ValueError("Source must be a file path (str) or pandas DataFrame.")

    df = normalize_columns(df)

    # Validate presence of minimum required financial fields
    required_financial_fields = ["sanctioned_amount", "expenditure_amount"]
    missing = [f for f in required_financial_fields if f not in df.columns]
    if missing:
        raise KeyError(
            f"Dataset missing essential columns: {missing}. "
            f"Available columns: {list(df.columns)}"
        )

    return df


def load_and_merge_generated_dataset(
    data_dir: str = "data",
    include_photos: bool = True,
) -> pd.DataFrame:
    """
    Loads and merges the relational CSV tables generated by generate_data.py:
    1. data/projects.csv (Master project records, categories, sanctioned budgets, dates)
    2. data/utilization.csv (Actual utilized funds & physical completion percentage)
    3. data/photo_evidence.csv (Optional: GPS distance deviations & duplicate photo flags)

    Returns a clean, unified DataFrame ready for model training or inference.
    """
    projects_path = os.path.join(data_dir, "projects.csv")
    utilization_path = os.path.join(data_dir, "utilization.csv")
    photo_path = os.path.join(data_dir, "photo_evidence.csv")

    if not os.path.exists(projects_path):
        raise FileNotFoundError(
            f"Projects master table not found at: {projects_path}. "
            f"Please run 'python generate_data.py' first to populate the {data_dir}/ directory."
        )
    if not os.path.exists(utilization_path):
        raise FileNotFoundError(
            f"Utilization table not found at: {utilization_path}. "
            f"Please run 'python generate_data.py' first to populate the {data_dir}/ directory."
        )

    print(f"[*] Ingesting relational tables from '{data_dir}/'...")
    projects_df = pd.read_csv(projects_path)
    utilization_df = pd.read_csv(utilization_path)

    projects_df = normalize_columns(projects_df)
    utilization_df = normalize_columns(utilization_df)

    # Merge projects with utilization on project_id
    merged = pd.merge(
        projects_df,
        utilization_df,
        on="project_id",
        how="inner",
        suffixes=("", "_uc"),
    )

    # Optionally merge photo evidence
    if include_photos and os.path.exists(photo_path):
        photo_df = pd.read_csv(photo_path)
        photo_df = normalize_columns(photo_df)

        photo_cols = ["project_id"]
        for col in ["gps_distance_km", "duplicate_photo_flag", "gps_verification"]:
            if col in photo_df.columns:
                photo_cols.append(col)

        photo_sub = photo_df[photo_cols].drop_duplicates(subset=["project_id"])
        merged = pd.merge(
            merged,
            photo_sub,
            on="project_id",
            how="left",
            suffixes=("", "_photo"),
        )
        print(f"[+] Merged projects ({len(projects_df):,} rows) with utilization and photo evidence.")
    else:
        print(f"[+] Merged projects ({len(projects_df):,} rows) with utilization.")

    merged = normalize_columns(merged)
    return merged


# ---------------------------------------------------------------------------
# 2. Domain Feature Engineering (MPLADS Fraud Indicators)
# ---------------------------------------------------------------------------

class MPLADSFeatureEngineer:
    """
    Extracts anti-corruption and fraud indicators tailored to government works:
    - Fund-Progress Mismatch (Money spent vs actual physical progress on ground)
    - Cost Overrun Ratio (Expenditure vs Sanctioned Budget)
    - Fund Release Utilization (Expenditure vs Released funds)
    - Sanction Discrepancy (Sanctioned vs Recommended amount)
    - Sector Cost Deviations (Z-score / ratio against category medians)
    """

    def __init__(self):
        self.scaler = RobustScaler()
        self.fitted = False
        self.feature_names: List[str] = []
        self.category_sanction_medians: Dict[str, float] = {}
        self.overall_median_sanctioned: float = 0.0
        self.category_unit_cost_medians: Dict[str, float] = {}
        self.overall_median_unit_cost: float = 0.0

    def fit(self, df: pd.DataFrame) -> "MPLADSFeatureEngineer":
        """Calculates category baselines and fits numerical scalers."""
        df = normalize_columns(df)

        sanctioned = pd.to_numeric(df.get("sanctioned_amount", 0.0), errors="coerce").fillna(0.0)
        expenditure = pd.to_numeric(df.get("expenditure_amount", 0.0), errors="coerce").fillna(0.0)
        physical_pct = pd.to_numeric(df.get("physical_progress_pct", 0.0), errors="coerce").fillna(0.0)
        unit_costs = expenditure / (physical_pct + 1.0)

        # Baseline category metrics (sanctioned budget and unit cost efficiency)
        if "category" in df.columns:
            df_temp = df.copy()
            df_temp["_sanct"] = sanctioned
            df_temp["_unit_cost"] = unit_costs

            self.category_sanction_medians = df_temp.groupby("category")["_sanct"].median().to_dict()
            self.category_unit_cost_medians = df_temp.groupby("category")["_unit_cost"].median().to_dict()

        self.overall_median_sanctioned = float(sanctioned.median()) if len(sanctioned) > 0 else 1000000.0
        self.overall_median_unit_cost = float(unit_costs.median()) if len(unit_costs) > 0 else 10000.0

        features_df = self._derive_indicators(df)
        self.feature_names = list(features_df.columns)
        self.scaler.fit(features_df.values)
        self.fitted = True
        return self

    def transform(self, df: pd.DataFrame) -> np.ndarray:
        """Transforms raw dataframe into scaled numerical feature array."""
        if not self.fitted:
            raise RuntimeError("FeatureEngineer must be fitted before calling transform.")
        df = normalize_columns(df)
        features_df = self._derive_indicators(df)
        # Ensure identical column order
        features_df = features_df.reindex(columns=self.feature_names, fill_value=0.0)
        return self.scaler.transform(features_df.values)

    def fit_transform(self, df: pd.DataFrame) -> np.ndarray:
        """Fits and transforms in a single step."""
        return self.fit(df).transform(df)

    def _derive_indicators(self, df: pd.DataFrame) -> pd.DataFrame:
        """Calculates domain specific fraud features."""
        feats = pd.DataFrame(index=df.index)

        # Base amounts (with zero-division prevention)
        sanctioned = pd.to_numeric(df.get("sanctioned_amount", 0.0), errors="coerce").fillna(0.0)
        expenditure = pd.to_numeric(df.get("expenditure_amount", 0.0), errors="coerce").fillna(0.0)
        released = pd.to_numeric(df.get("released_amount", sanctioned), errors="coerce").fillna(sanctioned)
        recommended = pd.to_numeric(df.get("recommended_amount", sanctioned), errors="coerce").fillna(sanctioned)
        physical_pct = pd.to_numeric(df.get("physical_progress_pct", 0.0), errors="coerce").fillna(0.0)

        eps = 1.0  # INR 1 smoothing epsilon to prevent division by zero

        # Indicator 1: Cost Overrun Ratio (Expenditure vs Sanctioned)
        feats["cost_overrun_ratio"] = expenditure / (sanctioned + eps)

        # Indicator 2: Release Utilization Ratio (Expenditure vs Released)
        feats["release_utilization_ratio"] = expenditure / (released + eps)

        # Indicator 3: Sanction-to-Recommended Ratio
        feats["sanction_ratio"] = sanctioned / (recommended + eps)

        # Indicator 4: Financial Progress Percentage (Capped at 200% for extreme outlier detection)
        financial_pct = np.clip((expenditure / (sanctioned + eps)) * 100.0, 0.0, 200.0)
        feats["financial_progress_pct"] = financial_pct

        # Indicator 5: Physical Progress Percentage
        feats["physical_progress_pct"] = physical_pct

        # Indicator 6: Progress Gap (Crucial Ghost Work Flag: Money spent with little physical work)
        feats["progress_gap"] = financial_pct - physical_pct

        # Indicator 7: Cost Spent per Unit of Physical Progress
        unit_cost = expenditure / (physical_pct + 1.0)
        feats["cost_per_progress_unit"] = unit_cost

        # Indicator 8: Category Sanction Ratio (Budget scale vs sector baseline)
        if "category" in df.columns:
            cat_sanct_median = df["category"].map(self.category_sanction_medians).fillna(self.overall_median_sanctioned)
            cat_unit_median = df["category"].map(self.category_unit_cost_medians).fillna(self.overall_median_unit_cost)
        else:
            cat_sanct_median = self.overall_median_sanctioned
            cat_unit_median = self.overall_median_unit_cost

        feats["category_sanction_ratio"] = np.clip(sanctioned / (cat_sanct_median + eps), 0.2, 5.0)

        # Indicator 9: Category Unit Cost Ratio (Cost efficiency per % progress vs sector baseline)
        feats["category_unit_cost_ratio"] = np.clip(unit_cost / (cat_unit_median + eps), 0.2, 5.0)

        # Indicator 10: Temporal Completion Delay (Days past expected deadline)
        if "expected_completion_date" in df.columns and "actual_completion_date" in df.columns:
            exp_dt = pd.to_datetime(df["expected_completion_date"], errors="coerce")
            act_dt = pd.to_datetime(df["actual_completion_date"], errors="coerce")
            delays = (act_dt - exp_dt).dt.days.fillna(0.0)
            feats["completion_delay_days"] = np.clip(delays, -30.0, 365.0)
        elif "completion_delay_days" in df.columns:
            feats["completion_delay_days"] = np.clip(
                pd.to_numeric(df["completion_delay_days"], errors="coerce").fillna(0.0), -30.0, 365.0
            )
        else:
            feats["completion_delay_days"] = 0.0

        # Indicator 11: Geospatial Discrepancy (Distance in KM from claimed coordinates)
        if "gps_distance_km" in df.columns:
            feats["gps_distance_km"] = np.clip(
                pd.to_numeric(df["gps_distance_km"], errors="coerce").fillna(0.0), 0.0, 200.0
            )
        else:
            feats["gps_distance_km"] = 0.0

        # Indicator 12: Duplicate Photographic Evidence Flag (1.0 for duplicated image hash)
        if "duplicate_photo_flag" in df.columns:
            dup_s = df["duplicate_photo_flag"].astype(str).str.strip().str.lower()
            feats["duplicate_photo_flag"] = dup_s.isin(["yes", "true", "1"]).astype(float)
        else:
            feats["duplicate_photo_flag"] = 0.0

        # Fill any remaining NaNs or Infs
        feats = feats.replace([np.inf, -np.inf], np.nan).fillna(0.0)

        return feats


# ---------------------------------------------------------------------------
# 3. Anomaly Explainer (Human-Readable Reasoning)
# ---------------------------------------------------------------------------

def explain_fraud_reasons(
    row: pd.Series,
    risk_score: float,
    category_sanction_median: float = 0.0,
    category_unit_cost_median: float = 0.0,
) -> List[str]:
    """
    Generates human-readable explanations for judges and audit officers.
    Translates model findings into actionable fraud red flags.
    """
    reasons = []

    # Priority 1: Physical / Photographic Evidence Checks
    # Evaluated before financial health checks so physical discrepancies are never suppressed.
    gps_dist = float(row.get("gps_distance_km", 0.0)) if pd.notna(row.get("gps_distance_km", 0.0)) else 0.0
    if gps_dist >= 5.0:
        reasons.append(
            f"Geospatial Discrepancy: Evidence photo location is {gps_dist:.1f} km away from registered project site."
        )

    dup_photo = str(row.get("duplicate_photo_flag", "No")).strip().lower()
    if dup_photo in ["yes", "true", "1"]:
        reasons.append(
            "Duplicate Photographic Evidence: Inspection image hash matches an existing project record."
        )

    sanctioned = float(row.get("sanctioned_amount", 0.0))
    expenditure = float(row.get("expenditure_amount", 0.0))
    released = float(row.get("released_amount", sanctioned))
    recommended = float(row.get("recommended_amount", sanctioned))
    physical_pct = float(row.get("physical_progress_pct", 0.0))

    fin_pct = (expenditure / (sanctioned + 1.0)) * 100.0
    gap = fin_pct - physical_pct
    cost_ratio = expenditure / (sanctioned + 1.0)
    release_ratio = expenditure / (released + 1.0)
    sanct_ratio = sanctioned / (recommended + 1.0)
    unit_cost = expenditure / (physical_pct + 1.0)

    # Health Check: If the project is strictly within sanctioned budget, has zero progress lag,
    # has no sanction anomaly, AND has no physical/photo red flags, it is a healthy execution.
    is_healthy = (cost_ratio <= 1.02) and (gap <= 5.0) and (sanct_ratio <= 1.20)
    if is_healthy and risk_score < 60.0 and not reasons:
        return ["Within normal operational and financial parameters."]

    # Rule 1: High financial expenditure with low physical progress (Ghost Project / Fund Siphoning)
    if gap >= 35.0:
        reasons.append(
            f"Severe Fund-Progress Mismatch: {fin_pct:.1f}% funds expended while physical progress is only {physical_pct:.1f}% (Gap: {gap:.1f}%)."
        )
    elif gap >= 20.0:
        reasons.append(
            f"Moderate Progress Lag: Financial burn ({fin_pct:.1f}%) significantly outpaces on-ground completion ({physical_pct:.1f}%)."
        )

    # Rule 2: Cost Overrun
    if cost_ratio >= 1.25:
        reasons.append(
            f"Severe Cost Overrun: Actual expenditure is {cost_ratio:.2f}x of sanctioned budget (INR {expenditure:,.0f} spent vs INR {sanctioned:,.0f} sanctioned)."
        )
    elif cost_ratio > 1.05:
        reasons.append(
            f"Budget Exceeded: Expenditure exceeds sanctioned limit by {((cost_ratio - 1.0) * 100):.1f}%."
        )

    # Rule 3: Fund Overdraw (Expenditure > Released amount)
    if release_ratio >= 1.20:
        reasons.append(
            f"Unauthorized Overdraw: Expenditure is {release_ratio:.2f}x the funds officially released."
        )

    # Rule 4: Excessive Sanction Padding (Sanctioned far exceeds recommendation)
    if sanct_ratio >= 1.50:
        reasons.append(
            f"Sanction Discrepancy: Sanctioned amount is {sanct_ratio:.2f}x of recommended estimate (INR {sanctioned:,.0f} vs INR {recommended:,.0f})."
        )

    # Rule 5: Sector Unit-Cost Inefficiency (Expenditure per % progress is abnormal AND progress is lagging)
    if category_unit_cost_median > 0:
        unit_ratio = unit_cost / category_unit_cost_median
        if unit_ratio >= 2.5 and gap >= 15.0:
            reasons.append(
                f"Sector Unit-Cost Inefficiency: Expenditure per progress unit is {unit_ratio:.1f}x higher than sector median."
            )

    # Rule 6: Sector Budget Outlier (Abnormally high sanctioned budget combined with budget strain)
    if category_sanction_median > 0:
        sanct_scale_ratio = sanctioned / category_sanction_median
        if sanct_scale_ratio >= 2.5 and (cost_ratio > 1.05 or gap > 20.0):
            reasons.append(
                f"Sector Budget Outlier: Sanctioned budget is {sanct_scale_ratio:.1f}x higher than sector median."
            )

    # Rule 7: Project Completion Delay
    delay_days = 0.0
    if "completion_delay_days" in row and pd.notna(row["completion_delay_days"]):
        delay_days = float(row["completion_delay_days"])
    elif "expected_completion_date" in row and "actual_completion_date" in row:
        exp_dt = pd.to_datetime(row["expected_completion_date"], errors="coerce")
        act_dt = pd.to_datetime(row["actual_completion_date"], errors="coerce")
        if pd.notna(exp_dt) and pd.notna(act_dt):
            delay_days = float((act_dt - exp_dt).days)

    if delay_days >= 45.0:
        reasons.append(
            f"Chronic Project Delay: Execution was delayed by {delay_days:.0f} days past the expected completion deadline."
        )

    # Fallback if isolation forest flagged high multidimensional anomaly without a single extreme breach
    if not reasons and risk_score >= 60.0:
        reasons.append(
            "Multivariate Anomaly: Joint distribution of financial burn, project scale, and progress significantly deviates from historic norms."
        )

    return reasons


# ---------------------------------------------------------------------------
# 4. Main Model: MPLADSFraudDetector (Isolation Forest)
# ---------------------------------------------------------------------------

class MPLADSFraudDetector:
    """
    Modular Anomaly Detection Engine for MPLADS projects using Isolation Forest.

    Provides:
    - fit(df)
    - predict(df)
    - predict_with_scores(df) -> Returns DataFrame with is_anomaly, risk_score (0-100), and fraud_reasons
    - save(filepath) / load(filepath)
    """

    def __init__(
        self,
        contamination: Union[str, float] = 0.08,
        n_estimators: int = 150,
        random_state: int = 42,
    ):
        """
        Parameters:
        - contamination: Expected proportion of outliers (e.g. 0.08 = ~8% anomalies).
        - n_estimators: Number of isolation trees.
        - random_state: Seed for reproducibility.
        """
        self.contamination = contamination
        self.n_estimators = n_estimators
        self.random_state = random_state

        self.model = IsolationForest(
            contamination=self.contamination,
            n_estimators=self.n_estimators,
            random_state=self.random_state,
            n_jobs=1,
        )
        self.engineer = MPLADSFeatureEngineer()
        self.is_fitted = False

        # Internal score thresholds for 0-100 calibration
        self.min_score_val = -0.5
        self.max_score_val = 0.5

    def fit(self, df: pd.DataFrame) -> "MPLADSFraudDetector":
        """Fits feature engineer and Isolation Forest on MPLADS dataset."""
        df_clean = normalize_columns(df)
        X = self.engineer.fit_transform(df_clean)
        self.model.fit(X)

        # Calibration parameters for normalizing risk scores to 0-100
        raw_decision_scores = self.model.decision_function(X)
        self.min_score_val = float(np.min(raw_decision_scores))
        self.max_score_val = float(np.max(raw_decision_scores))

        self.is_fitted = True
        return self

    def predict(self, df: pd.DataFrame) -> np.ndarray:
        """
        Returns binary predictions from Isolation Forest:
        1 for Normal, -1 for Anomaly
        """
        if not self.is_fitted:
            raise RuntimeError("Model must be fitted before running predictions.")
        df_clean = normalize_columns(df)
        X = self.engineer.transform(df_clean)
        return self.model.predict(X)

    def compute_risk_scores(self, decision_scores: np.ndarray) -> np.ndarray:
        """
        Converts Isolation Forest decision scores into a 0 to 100 Risk Score.
        Lower decision score indicates deeper isolation (higher anomaly).
        We invert and scale so:
        - 0-40: Normal / Low Risk
        - 41-65: Moderate Risk
        - 66-100: High Risk / Probable Fraud
        """
        span = (self.max_score_val - self.min_score_val) + 1e-8
        # Invert: decision_score near min_score_val becomes high risk
        normalized = (self.max_score_val - decision_scores) / span
        risk_scores = np.clip(normalized * 100.0, 0.0, 100.0)
        return np.round(risk_scores, 2)

    def predict_with_scores(self, df: pd.DataFrame, risk_threshold: float = 65.0) -> pd.DataFrame:
        """
        Runs the complete detection pipeline and enriches original records with:
        - is_anomaly: True/False
        - risk_score: 0.0 to 100.0
        - fraud_reasons: List of clear, understandable flags
        - risk_level: 'High', 'Medium', 'Low'
        """
        if not self.is_fitted:
            raise RuntimeError("Model must be fitted before running predictions.")

        df_clean = normalize_columns(df)
        X = self.engineer.transform(df_clean)

        raw_preds = self.model.predict(X)  # -1 = anomaly, 1 = normal
        decision_scores = self.model.decision_function(X)
        risk_scores = self.compute_risk_scores(decision_scores)

        results = df.copy().reset_index(drop=True)
        results["is_anomaly"] = (raw_preds == -1) | (risk_scores >= risk_threshold)
        results["risk_score"] = risk_scores

        # Categorize risk level
        results["risk_level"] = pd.cut(
            results["risk_score"],
            bins=[-np.inf, 40.0, 65.0, np.inf],
            labels=["Low", "Medium", "High"],
        )

        # Generate human-readable reasons for flagged records
        reasons_list = []
        df_clean_reset = df_clean.reset_index(drop=True)
        for idx, row in df_clean_reset.iterrows():
            curr_score = risk_scores[idx] if idx < len(risk_scores) else 0.0
            cat = str(row.get("category", ""))
            cat_sanct_median = self.engineer.category_sanction_medians.get(
                cat, self.engineer.overall_median_sanctioned
            )
            cat_unit_median = self.engineer.category_unit_cost_medians.get(
                cat, self.engineer.overall_median_unit_cost
            )

            if results.loc[idx, "is_anomaly"]:
                r = explain_fraud_reasons(
                    row,
                    curr_score,
                    category_sanction_median=cat_sanct_median,
                    category_unit_cost_median=cat_unit_median,
                )
                reasons_list.append("; ".join(r) if r else "Unusual combination of financial and progress parameters.")
            else:
                reasons_list.append("Within expected operational parameters.")

        results["fraud_reasons"] = reasons_list

        return results

    def save(self, filepath: str) -> None:
        """Persists trained detector and preprocessing state to disk."""
        if not self.is_fitted:
            raise RuntimeError("Cannot save an unfitted model.")
        parent_dir = os.path.dirname(os.path.abspath(filepath))
        if parent_dir:
            os.makedirs(parent_dir, exist_ok=True)
        joblib.dump(self, filepath)
        print(f"[+] Model successfully saved to: {filepath}")

    @staticmethod
    def load(filepath: str) -> "MPLADSFraudDetector":
        """Loads a persisted MPLADSFraudDetector instance."""
        if not os.path.exists(filepath):
            raise FileNotFoundError(f"Model file not found at: {filepath}")
        detector = joblib.load(filepath)
        print(f"[+] Model successfully loaded from: {filepath}")
        return detector


# ---------------------------------------------------------------------------
# 5. Self-Test & Demonstration Utility
# ---------------------------------------------------------------------------

def generate_mock_mplads_data() -> pd.DataFrame:
    """
    Generates a realistic synthetic mini-dataset of MPLADS developmental works.
    Includes typical legitimate works and 4 planted fraud archetypes:
    1. Ghost Project: 95.8% funds spent with only 5% physical progress.
    2. Severe Cost Overrun: Spent INR 46 Lakhs on a INR 25 Lakh sanctioned rural road.
    3. Severe Stalled Drain Work: 100% funds released and spent, 12% progress.
    4. Extreme Sector Cost Inflation: Small school repair sanctioned at 4.8x recommended.
    """
    np.random.seed(42)

    CATEGORY_BUDGETS = {
        "Drinking Water": [600000, 800000, 1200000],
        "Rural Roads": [2000000, 3000000, 4000000],
        "Sanitation & Drainage": [800000, 1200000, 1500000],
        "Health Infrastructure": [2500000, 3500000, 4500000],
        "Education & Schools": [1200000, 1800000, 2500000],
        "Community Centers": [1000000, 1500000, 2000000],
    }

    records = []
    categories = list(CATEGORY_BUDGETS.keys())

    # 1. Generate 20 typical normal projects
    for i in range(1, 21):
        cat = categories[i % len(categories)]
        sanctioned = float(np.random.choice(CATEGORY_BUDGETS[cat]))
        recom = sanctioned * np.random.uniform(0.95, 1.05)
        released = sanctioned * np.random.uniform(0.80, 1.00)

        # Progress aligned with expenditure
        phys_pct = float(np.random.uniform(25.0, 98.0))
        # Expenditure directly aligned with progress (+/- 3% variation), strictly within budget
        spent = (sanctioned * (phys_pct / 100.0)) * np.random.uniform(0.96, 1.02)
        spent = min(spent, sanctioned)

        records.append({
            "project_id": f"MPLAD-2024-{i:03d}",
            "state": "Maharashtra",
            "constituency": "Pune",
            "category": cat,
            "recommended_amount": round(recom, -3),
            "sanctioned_amount": round(sanctioned, -3),
            "released_amount": round(released, -3),
            "expenditure_amount": round(spent, -3),
            "physical_progress_pct": round(phys_pct, 1),
            "contractor_id": f"CONT-{(i % 5) + 101}",
            "status": "Completed" if phys_pct >= 95 else "In Progress",
            "expected_completion_date": "2025-06-30",
            "actual_completion_date": "2025-06-25",
            "gps_distance_km": round(float(np.random.uniform(0.05, 0.40)), 2),
            "duplicate_photo_flag": "No",
        })

    # 2. Plant Anomaly 1: Ghost Project (Money spent, practically 0 ground work + Location mismatch)
    records.append({
        "project_id": "MPLAD-2024-FRAUD-01",
        "state": "Maharashtra",
        "constituency": "Pune",
        "category": "Drinking Water",
        "recommended_amount": 1200000,
        "sanctioned_amount": 1200000,
        "released_amount": 1200000,
        "expenditure_amount": 1150000,  # 95.8% spent
        "physical_progress_pct": 5.0,   # Only 5% on ground (Gap: 90.8%)
        "contractor_id": "CONT-GHOST-99",
        "status": "In Progress",
        "expected_completion_date": "2025-04-15",
        "actual_completion_date": "",
        "gps_distance_km": 42.5,  # 42.5 km mismatch!
        "duplicate_photo_flag": "No",
    })

    # 3. Plant Anomaly 2: Severe Cost Overrun / Fund Siphoning + Chronic Delay
    records.append({
        "project_id": "MPLAD-2024-FRAUD-02",
        "state": "Maharashtra",
        "constituency": "Pune",
        "category": "Rural Roads",
        "recommended_amount": 2500000,
        "sanctioned_amount": 2500000,
        "released_amount": 2500000,
        "expenditure_amount": 4600000,  # 1.84x sanctioned budget
        "physical_progress_pct": 60.0,
        "contractor_id": "CONT-INFLATE-88",
        "status": "In Progress",
        "expected_completion_date": "2025-03-01",
        "actual_completion_date": "2025-06-15",  # 106 days delay
        "gps_distance_km": 0.8,
        "duplicate_photo_flag": "No",
    })

    # 4. Plant Anomaly 3: Full Funds Disbursed & Spent on Stalled Sanitation Drain + Delay
    records.append({
        "project_id": "MPLAD-2024-FRAUD-03",
        "state": "Maharashtra",
        "constituency": "Pune",
        "category": "Sanitation & Drainage",
        "recommended_amount": 1200000,
        "sanctioned_amount": 1200000,
        "released_amount": 1200000,
        "expenditure_amount": 1200000,  # 100% spent
        "physical_progress_pct": 12.0,  # 12% progress (Gap: 88.0%)
        "contractor_id": "CONT-STALL-77",
        "status": "In Progress",
        "expected_completion_date": "2025-02-10",
        "actual_completion_date": "2025-05-20",  # 99 days delay
        "gps_distance_km": 1.1,
        "duplicate_photo_flag": "No",
    })

    # 5. Plant Anomaly 4: Massive Sanction Inflation & Collusion + Duplicate Evidence Photo
    records.append({
        "project_id": "MPLAD-2024-FRAUD-04",
        "state": "Maharashtra",
        "constituency": "Pune",
        "category": "Education & Schools",
        "recommended_amount": 1000000,
        "sanctioned_amount": 4800000,  # Sanctioned 4.8x recommended
        "released_amount": 4800000,
        "expenditure_amount": 4750000,
        "physical_progress_pct": 45.0,  # Gap: 54.0%
        "contractor_id": "CONT-COLLUDE-66",
        "status": "In Progress",
        "expected_completion_date": "2025-05-01",
        "actual_completion_date": "2025-07-20",  # 80 days delay
        "gps_distance_km": 18.2,  # 18.2 km mismatch
        "duplicate_photo_flag": "Yes",  # Duplicate photo!
    })

    return pd.DataFrame(records)


def run_self_test():
    """
    Executes an end-to-end self-test to demonstrate the prototype:
    1. Generates mock MPLADS data.
    2. Trains the Isolation Forest model.
    3. Detects anomalies and computes 0-100 risk scores.
    4. Displays understandable fraud reasons.
    5. Saves and re-loads the model.
    """
    print("\n" + "=" * 75)
    print("      MPLADS AI FRAUD DETECTION SYSTEM - SIH PROTOTYPE DEMO")
    print("=" * 75)

    # 1. Load mock data
    print("\n[Step 1] Loading synthetic MPLADS dataset (20 normal works + 4 fraud cases)...")
    df = generate_mock_mplads_data()
    print(f"Total projects loaded: {len(df)}")

    # 2. Train Model
    print("\n[Step 2] Engineering MPLADS fraud indicators & training Isolation Forest...")
    detector = MPLADSFraudDetector(contamination=0.17, random_state=42)
    detector.fit(df)
    print("[+] Model trained successfully.")

    # 3. Predict & Score
    print("\n[Step 3] Detecting anomalies & calculating 0-100 Risk Scores...")
    scored_df = detector.predict_with_scores(df, risk_threshold=60.0)

    # 4. Display Results
    flagged = scored_df[scored_df["is_anomaly"]].sort_values(by="risk_score", ascending=False)
    print(f"\n[Step 4] Anomalies Flagged: {len(flagged)} out of {len(df)} projects")
    print("-" * 75)

    cols_to_show = [
        "project_id",
        "category",
        "sanctioned_amount",
        "expenditure_amount",
        "physical_progress_pct",
        "risk_score",
        "risk_level",
    ]

    print(flagged[cols_to_show].to_string(index=False))

    print("\n" + "-" * 75)
    print("DETAILED FRAUD REASONING REPORT (FOR AUDITORS / SIH JURY)")
    print("-" * 75)

    for _, row in flagged.iterrows():
        print(f"\n[!] Project ID: {row['project_id']} | Category: {row['category']}")
        print(f"    Sanctioned: INR {row['sanctioned_amount']:,.0f} | Expended: INR {row['expenditure_amount']:,.0f} | Physical Progress: {row['physical_progress_pct']}%")
        print(f"    Risk Score: {row['risk_score']}/100 [Level: {row['risk_level']}]")
        print(f"    Reasons   : {row['fraud_reasons']}")

    # 5. Test Persistence
    print("\n[Step 5] Testing model export and re-import (joblib)...")
    model_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "mplads_fraud_model.joblib")
    detector.save(model_path)
    loaded_detector = MPLADSFraudDetector.load(model_path)
    test_preds = loaded_detector.predict(df.head(3))
    print(f"[+] Reloaded model verification output for first 3 records: {test_preds}")

    # 6. Check for real data directory
    real_data_dir = "data"
    proj_csv = os.path.join(real_data_dir, "projects.csv")
    util_csv = os.path.join(real_data_dir, "utilization.csv")
    if os.path.exists(proj_csv) and os.path.exists(util_csv):
        print(f"\n[*] Real generated dataset detected in '{real_data_dir}/'!")
        print(f"    Run 'load_and_merge_generated_dataset(\"{real_data_dir}\")' to analyze the full relational dataset.")
    else:
        print(f"\n[*] Note: Real dataset not found in '{real_data_dir}/'. Run 'python generate_data.py' to generate it.")

    print("\n" + "=" * 75)
    print("      PROTOTYPE SELF-TEST COMPLETED SUCCESSFULLY!")
    print("=" * 75 + "\n")


if __name__ == "__main__":
    run_self_test()
